version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=your_openweather_api_key
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
