version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=your_openweather_api_key
    depends_on:
      - ollama
    networks:
      - tutorial-net

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   entrypoint: ["ollama", "serve"]  # 서버 실행


  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - tutorial-vol:/ollama
    networks:
      - tutorial-net
    entrypoint: ["/usr/bin/bash", "/pull-llama3_2.sh"]

networks:
  tutorial-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local